import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Eye, EyeOff, HeartPulse } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { apiRequest } from '../../services/apiClient';
import { useAuth } from '../../app/auth/auth-context';

export function PatientLogin() {
  const { t } = useTranslation(); const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [form,setForm]=useState({username:'',password:''}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [showPassword,setShowPassword]=useState(false);
  async function submit(e){e.preventDefault();setLoading(true);setError('');try{const data=await apiRequest('/api/auth/login',{method:'POST',body:JSON.stringify(form)});if(data.user.role!=='PATIENT')throw new Error(t('patientAccountRequired'));login(data.user,data.token);navigate('/patient');}catch(err){setError(err.message);}finally{setLoading(false)}}
  return <AuthShell title={t('patientLogin')}>{location.state?.message&&<div className="patient-alert success">{location.state.message}</div>}<form onSubmit={submit}><Field label={t('phoneOrEmail')} value={form.username} onChange={username=>setForm({...form,username})} autoComplete="username"/><label className="patient-field">{t('password')}<span style={{position:'relative'}}><input style={{width:'100%',paddingInlineEnd:'3rem'}} type={showPassword?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} autoComplete="current-password" required/><button type="button" aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(!showPassword)} style={{position:'absolute',insetInlineEnd:'.45rem',top:'.25rem',width:'38px',height:'38px',border:0,background:'transparent',color:'var(--color-text-secondary)',cursor:'pointer'}}>{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></span></label>{error&&<Alert>{error}</Alert>}<button className="patient-button" disabled={loading} aria-busy={loading}>{loading?t('loading'):t('login')}</button></form><p><Link to="/register">{t('createPatientAccount')}</Link></p></AuthShell>;
}
export function PatientRegister(){const{t}=useTranslation();const navigate=useNavigate();const[form,setForm]=useState({fullName:'',phone:'',email:'',dateOfBirth:'',gender:'MALE',password:'',confirmPassword:''});const[challenge,setChallenge]=useState(null);const[code,setCode]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);
async function register(e){e.preventDefault();if(form.password!==form.confirmPassword){setError(t('passwordMismatch'));return;}setLoading(true);setError('');try{const payload={...form};delete payload.confirmPassword;const data=await apiRequest('/api/patient-auth/register',{method:'POST',body:JSON.stringify({...payload,email:payload.email||undefined})});setChallenge(data);}catch(err){setError(err.message)}finally{setLoading(false)}}
async function verify(e){e.preventDefault();setLoading(true);setError('');try{const data=await apiRequest('/api/patient-auth/verify',{method:'POST',body:JSON.stringify({challengeId:challenge.challengeId,code})});navigate('/patient-login',{state:{message:data.state==='MATCH_REQUIRES_VERIFICATION'?t('claimAfterLogin'):t('accountVerified')}})}catch(err){setError(err.message)}finally{setLoading(false)}}
return <AuthShell title={t('createPatientAccount')}>{!challenge?<form onSubmit={register}><Field label={t('fullName')} value={form.fullName} onChange={fullName=>setForm({...form,fullName})}/><Field label={t('phone')} value={form.phone} onChange={phone=>setForm({...form,phone})}/><Field label={t('emailOptional')} type="email" value={form.email} onChange={email=>setForm({...form,email})}/><Field label={t('dateOfBirth')} type="date" value={form.dateOfBirth} onChange={dateOfBirth=>setForm({...form,dateOfBirth})}/><label className="patient-field">{t('gender')}<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="MALE">{t('male')}</option><option value="FEMALE">{t('female')}</option></select></label><Field label={t('password')} type="password" value={form.password} onChange={password=>setForm({...form,password})}/><Field label={t('confirmPassword')} type="password" value={form.confirmPassword} onChange={confirmPassword=>setForm({...form,confirmPassword})}/>{error&&<Alert>{error}</Alert>}<button className="patient-button" disabled={loading}>{loading?t('loading'):t('createAccount')}</button></form>:<form onSubmit={verify}><p>{t('verificationCodePrompt')}</p>{challenge.developmentCode&&<div className="patient-alert success">{t('developmentCode')}: <strong>{challenge.developmentCode}</strong></div>}<Field label={t('verificationCode')} value={code} onChange={setCode}/>{error&&<Alert>{error}</Alert>}<button className="patient-button" disabled={loading}>{loading?t('loading'):t('verify')}</button></form>}</AuthShell>}
export function PatientClaim(){const{t}=useTranslation();const[form,setForm]=useState({code:'',dateOfBirth:''});const[message,setMessage]=useState('');const[error,setError]=useState('');async function submit(e){e.preventDefault();setError('');try{const data=await apiRequest('/api/patient-auth/claim',{method:'POST',body:JSON.stringify(form)});setMessage(data.state)}catch(err){setError(err.message)}}return <section className="patient-card"><h1>{t('claimRecord')}</h1><p>{t('claimInstructions')}</p><form onSubmit={submit}><Field label={t('claimCode')} value={form.code} onChange={code=>setForm({...form,code})}/><Field label={t('dateOfBirth')} type="date" value={form.dateOfBirth} onChange={dateOfBirth=>setForm({...form,dateOfBirth})}/>{error&&<Alert>{error}</Alert>}{message&&<div className="patient-alert success">{message}</div>}<button className="patient-button">{t('claimRecord')}</button></form></section>}
function AuthShell({title,children}){const{t}=useTranslation();return <main className="patient-auth-shell"><aside className="patient-auth-aside"><Link to="/"><HeartPulse size={24}/> {` ${t('brandName')}`}</Link><div><h2>{title}</h2><p>{t('secureAccessDescription')}</p></div></aside><div className="patient-auth-content"><section className="patient-card patient-auth"><h1>{title}</h1>{children}</section></div></main>};function Field({label,type='text',value,onChange,autoComplete}){return <label className="patient-field">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} autoComplete={autoComplete} required={type!=='email'}/></label>};function Alert({children}){return <div className="patient-alert error" role="alert">{children}</div>}
