import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Clock3, Plus, Save, Trash2 } from 'lucide-react';
import { apiErrorMessage, fetchWithAuth } from '../../services/staffApi';
import './adminSchedule.css';
import { selectScheduleVersion } from './scheduleVersion';

const blankPeriod = (dayOfWeek = 'MONDAY') => ({ dayOfWeek, startTime: '09:00', endTime: '17:00', slotDurationMinutes: 30, active: true, breaks: [] });
const clinicDate = (instant, timeZone) => { const values = Object.fromEntries(new Intl.DateTimeFormat('en', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(instant).map(({ type, value }) => [type, value])); return `${values.year}-${values.month}-${values.day}`; };

export default function AdminSchedulePanel({ t }) {
  const [doctors, setDoctors] = useState([]); const [doctorId, setDoctorId] = useState('');
  const [schedule, setSchedule] = useState(null); const [scheduleKind, setScheduleKind] = useState('empty'); const [periods, setPeriods] = useState([]); const [exceptions, setExceptions] = useState([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const [exceptionDate, setExceptionDate] = useState(''); const [exceptionReason, setExceptionReason] = useState('');
  const [clinicTimeZone, setClinicTimeZone] = useState('Africa/Khartoum');
  const label = (key, fallback) => t?.(key) || fallback;
  const selectedDoctor = useMemo(() => doctors.find((doctor) => doctor.id === doctorId), [doctors, doctorId]);
  const loadDoctors = async () => { const data = await (await fetchWithAuth('/api/appointments/doctors')).json(); setDoctors(Array.isArray(data) ? data : []); if (!doctorId && data?.[0]) setDoctorId(data[0].id); };
  const loadSchedule = async (id = doctorId) => { if (!id) return; setLoading(true); setError(''); try { const [schedules, ex] = await Promise.all([fetchWithAuth(`/api/admin/doctors/${id}/schedules`).then((r) => r.json()), fetchWithAuth(`/api/admin/doctors/${id}/schedule-exceptions`).then((r) => r.json())]); const selection = selectScheduleVersion(schedules, clinicDate(new Date(), clinicTimeZone)); setSchedule(selection.schedule); setScheduleKind(selection.kind); setPeriods(selection.schedule?.periods?.map((p) => ({ ...p, breaks: p.breaks || [] })) || []); setExceptions(Array.isArray(ex) ? ex : []); } catch (e) { setError(e.message || label('scheduleLoadError', 'Unable to load schedule.')); } finally { setLoading(false); } };
  useEffect(() => { Promise.all([loadDoctors(), fetchWithAuth('/api/public-config').then((response) => response.ok ? response.json() : null)]).then(([, config]) => { if (config?.clinicTimeZone) setClinicTimeZone(config.clinicTimeZone); }).catch(() => setError(label('scheduleLoadError', 'Unable to load schedule.'))); }, []);
  useEffect(() => { if (doctorId) loadSchedule(doctorId); }, [doctorId]);
  const updatePeriod = (index, patch) => setPeriods((current) => current.map((period, i) => i === index ? { ...period, ...patch } : period));
  const save = async (event) => { event.preventDefault(); if (saving || !doctorId) return; setSaving(true); setError(''); setSuccess(''); try { const now = new Date(); const today = clinicDate(now, clinicTimeZone); const clinicParts = clinicDate(now, clinicTimeZone).split('-').map(Number); const tomorrow = clinicDate(new Date(Date.UTC(clinicParts[0], clinicParts[1] - 1, clinicParts[2] + 1, 12)), clinicTimeZone); const currentIsEffective = Boolean(schedule?.id && schedule.effectiveFrom <= today); const body = { effectiveFrom: currentIsEffective ? tomorrow : (schedule?.effectiveFrom || today), active: true, periods: periods.map(({ id, createdAt, updatedAt, scheduleId, ...period }) => ({ ...period, breaks: (period.breaks || []).map(({ id: breakId, createdAt: bCreated, updatedAt: bUpdated, periodId, ...br }) => br) })) }; const url = currentIsEffective ? `/api/admin/doctors/${doctorId}/schedules` : (schedule?.id ? `/api/admin/doctors/${doctorId}/schedules/${schedule.id}` : `/api/admin/doctors/${doctorId}/schedules`); const response = await fetchWithAuth(url, { method: currentIsEffective || !schedule?.id ? 'POST' : 'PUT', body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(apiErrorMessage(data, label('scheduleSaveError', 'Unable to save schedule.'))); setSuccess(label('scheduleSaved', 'Schedule saved successfully.')); await loadSchedule(); } catch (e) { setError(e.message || label('scheduleSaveError', 'Unable to save schedule.')); } finally { setSaving(false); } };
  const addException = async (event) => { event.preventDefault(); if (!exceptionDate || saving) return; setSaving(true); setError(''); try { const response = await fetchWithAuth(`/api/admin/doctors/${doctorId}/schedule-exceptions/${exceptionDate}`, { method: 'PUT', body: JSON.stringify({ type: 'FULL_DAY_LEAVE', reason: exceptionReason || null, periods: [] }) }); const data = await response.json(); if (!response.ok) throw new Error(apiErrorMessage(data, label('exceptionSaveError', 'Unable to save exception.'))); setExceptionDate(''); setExceptionReason(''); setSuccess(label('exceptionSaved', 'Unavailable date saved.')); await loadSchedule(); } catch (e) { setError(e.message || label('exceptionSaveError', 'Unable to save exception.')); } finally { setSaving(false); } };
  const deactivateException = async (date) => { if (saving || !globalThis.confirm(label('exceptionConfirm', 'Restore availability for this date?'))) return; setSaving(true); try { const response = await fetchWithAuth(`/api/admin/doctors/${doctorId}/schedule-exceptions/${date}/status`, { method: 'PATCH', body: JSON.stringify({ active: false }) }); const data = await response.json(); if (!response.ok) throw new Error(apiErrorMessage(data, label('exceptionSaveError', 'Unable to update exception.'))); setSuccess(label('exceptionRestored', 'Availability restored.')); await loadSchedule(); } catch (e) { setError(e.message || label('exceptionSaveError', 'Unable to update exception.')); } finally { setSaving(false); } };
  if (loading && !doctors.length) return <div className="admin-schedule-panel" role="status">{label('loading', 'Loading…')}</div>;
  return <section className="admin-schedule-panel" aria-labelledby="admin-schedule-title">
    <header className="admin-schedule-header"><div><span className="admin-schedule-eyebrow"><CalendarDays size={16}/>{label('scheduleManagement', 'Schedule management')}</span><h2 id="admin-schedule-title">{label('scheduleTitle', 'Doctor availability')}</h2><p>{label('scheduleSubtitle', 'Manage recurring clinic hours and unavailable dates.')}</p></div><Clock3 size={28} aria-hidden="true"/></header>
    {error && <div className="badge badge-danger" role="alert">{error}</div>}{success && <div className="badge badge-success" role="status">{success}</div>}
    <label className="form-label" htmlFor="schedule-doctor">{label('selectDoctor', 'Doctor')}</label><select id="schedule-doctor" className="form-input" value={doctorId} onChange={(e) => setDoctorId(e.target.value)}><option value="">{label('selectDoctor', 'Select a doctor')}</option>{doctors.map((doctor) => <option key={doctor.id} value={doctor.id}>{doctor.fullNameEn || doctor.fullNameAr} — {doctor.specialty?.nameEn || doctor.specialtyEn || ''}</option>)}</select>
    {selectedDoctor && <p className="admin-schedule-doctor">{selectedDoctor.fullNameEn || selectedDoctor.fullNameAr} · {selectedDoctor.specialty?.nameEn || selectedDoctor.specialtyEn || selectedDoctor.specialty?.nameAr || selectedDoctor.specialtyAr || '—'}</p>}
    {scheduleKind === 'current' && <div className="admin-schedule-notice" role="note">{label('scheduleTomorrowNotice', 'Changes to the current schedule will take effect from tomorrow.')}</div>}
    {scheduleKind === 'future' && schedule && <div className="admin-schedule-notice" role="note">{t?.('scheduleFutureNotice', { date: schedule.effectiveFrom }) || `The selected schedule starts on ${schedule.effectiveFrom}.`}</div>}
    {!loading && !schedule && <p className="admin-schedule-empty">{label('scheduleEmpty', 'No normalized schedule yet. Add a working period to begin.')}</p>}
    <form onSubmit={save}><div className="admin-period-list">{periods.map((period, index) => <fieldset className="admin-period" key={period.id || index}><legend>{label(`weekday${period.dayOfWeek}`, period.dayOfWeek)}</legend><label><input type="checkbox" checked={period.active !== false} onChange={(e) => updatePeriod(index, { active: e.target.checked })}/> {label('workingDay', 'Working day')}</label><div className="admin-period-grid"><label>{label('startTime', 'Start')}<input className="form-input" type="time" value={period.startTime} onChange={(e) => updatePeriod(index, { startTime: e.target.value })}/></label><label>{label('endTime', 'End')}<input className="form-input" type="time" value={period.endTime} onChange={(e) => updatePeriod(index, { endTime: e.target.value })}/></label><label>{label('slotDuration', 'Slot duration')}<input className="form-input" type="number" min="1" max="1440" value={period.slotDurationMinutes} onChange={(e) => updatePeriod(index, { slotDurationMinutes: Number(e.target.value) })}/></label></div><div className="admin-breaks"><strong>{label('breaks', 'Breaks')}</strong>{(period.breaks || []).map((br, bi) => <div className="admin-break" key={br.id || bi}><input className="form-input" type="time" value={br.startTime} onChange={(e) => updatePeriod(index, { breaks: period.breaks.map((b, i) => i === bi ? { ...b, startTime: e.target.value } : b) })}/><input className="form-input" type="time" value={br.endTime} onChange={(e) => updatePeriod(index, { breaks: period.breaks.map((b, i) => i === bi ? { ...b, endTime: e.target.value } : b) })}/><button type="button" className="btn btn-secondary" onClick={() => updatePeriod(index, { breaks: period.breaks.filter((_, i) => i !== bi) })} aria-label={label('removeBreak', 'Remove break')}><Trash2 size={15}/></button></div>)}<button type="button" className="btn btn-secondary" onClick={() => updatePeriod(index, { breaks: [...(period.breaks || []), { startTime: '12:00', endTime: '13:00', active: true }] })}><Plus size={14}/> {label('addBreak', 'Add break')}</button></div><button type="button" className="btn btn-secondary" onClick={() => setPeriods((current) => current.filter((_, i) => i !== index))}>{label('removePeriod', 'Remove day')}</button></fieldset>)}</div><div className="admin-schedule-actions"><button type="button" className="btn btn-secondary" onClick={() => setPeriods((current) => [...current, blankPeriod()])}><Plus size={15}/> {label('addWorkingDay', 'Add working period')}</button><button type="submit" className="btn btn-primary" disabled={saving || !doctorId}><Save size={15}/> {saving ? label('saving', 'Saving…') : label('saveSchedule', 'Save schedule')}</button></div></form>
    <form className="admin-exception-form" onSubmit={addException}><h3>{label('unavailableDates', 'Unavailable dates')}</h3><div className="admin-period-grid"><label>{label('date', 'Date')}<input className="form-input" type="date" required value={exceptionDate} onChange={(e) => setExceptionDate(e.target.value)}/></label><label>{label('reason', 'Reason')}<input className="form-input" value={exceptionReason} onChange={(e) => setExceptionReason(e.target.value)} maxLength="500"/></label><button className="btn btn-primary" disabled={saving}>{label('markUnavailable', 'Mark unavailable')}</button></div>{exceptions.filter((item) => item.active).map((item) => <div className="admin-exception" key={item.id}><span>{item.date} — {item.reason || label('fullDayLeave', 'Full-day leave')}</span><button type="button" className="btn btn-secondary" onClick={() => deactivateException(item.date)}>{label('restoreDate', 'Restore')}</button></div>)}</form>
  </section>;
}
