import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { apiRequest } from '../../services/apiClient';

function useApi(path){const[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const reload=()=>{setLoading(true);apiRequest(path).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(reload,[path]);return{data,error,loading,reload}}
function State({loading,error,children}){if(loading)return <div className="patient-card">Loading…</div>;if(error)return <div className="patient-alert error" role="alert">{error}</div>;return children}
function Empty({children}){return <div className="patient-card patient-empty">{children}</div>}
const doctorName=(doctor,lang)=>lang==='ar'?doctor?.fullNameAr:doctor?.fullNameEn;

export function Dashboard(){const{t}=useTranslation();const profile=useApi('/api/patient/me');const appointments=useApi('/api/patient/appointments?group=upcoming');const labs=useApi('/api/patient/lab-results');const prescriptions=useApi('/api/patient/prescriptions');if(profile.error?.includes('not linked'))return <><div className="patient-alert error">{profile.error}</div><Link className="patient-button" to="/patient/claim">{t('claimRecord')}</Link></>;return <State loading={profile.loading} error={profile.error}><h1>{t('patientHome')}</h1><div className="patient-card"><h2>{t('welcome')}, {profile.data?.fullNameEn}</h2><Link className="patient-button" to="/patient/doctors">{t('bookAppointment')}</Link></div><div className="patient-grid"><Summary title={t('upcomingAppointments')} value={appointments.data?.length||0}/><Summary title={t('recentLabResults')} value={labs.data?.length||0}/><Summary title={t('prescriptions')} value={prescriptions.data?.length||0}/></div></State>}
function Summary({title,value}){return <div className="patient-card"><h3>{title}</h3><strong>{value}</strong></div>}

export function Doctors(){const{t,i18n}=useTranslation();const{data,error,loading}=useApi('/api/patient/doctors');return <State loading={loading} error={error}><h1>{t('doctors')}</h1>{!data?.length?<Empty>{t('noDoctors')}</Empty>:<div className="patient-grid">{data.map(d=><article className="patient-card" key={d.id}><h2>{doctorName(d,i18n.language)}</h2><p>{i18n.language==='ar'?d.specialtyAr:d.specialtyEn}</p><p>{Number(d.consultationFee).toLocaleString()} SDG</p><div className="patient-actions"><Link className="patient-button secondary" to={`/patient/doctors/${d.id}`}>{t('details')}</Link><Link className="patient-button" to={`/patient/book/${d.id}`}>{t('book')}</Link></div></article>)}</div>}</State>}
export function DoctorDetails(){const{id}=useParams();const{t,i18n}=useTranslation();const{data,error,loading}=useApi(`/api/patient/doctors/${id}`);return <State loading={loading} error={error}><article className="patient-card"><h1>{doctorName(data,i18n.language)}</h1><p>{i18n.language==='ar'?data.specialtyAr:data.specialtyEn}</p><p>{Number(data.consultationFee).toLocaleString()} SDG</p><Link className="patient-button" to={`/patient/book/${id}`}>{t('bookAppointment')}</Link></article></State>}
export function BookAppointment(){const{doctorId}=useParams();const{t}=useTranslation();const nav=useNavigate();const[date,setDate]=useState(''),[slots,setSlots]=useState([]),[time,setTime]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);useEffect(()=>{if(date)apiRequest(`/api/appointments/slots?doctorId=${doctorId}&date=${date}`).then(setSlots).catch(e=>setError(e.message))},[doctorId,date]);async function submit(e){e.preventDefault();setLoading(true);setError('');try{const app=await apiRequest('/api/patient/appointments',{method:'POST',body:JSON.stringify({doctorId,appointmentDate:date,appointmentTime:time})});nav(`/patient/appointments/${app.id}`)}catch(e){setError(e.message)}finally{setLoading(false)}}return <section className="patient-card"><h1>{t('bookAppointment')}</h1><form onSubmit={submit}><label className="patient-field">{t('selectDate')}<input type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>{setDate(e.target.value);setTime('')}}/></label>{date&&<fieldset className="patient-card"><legend>{t('selectTime')}</legend><div className="patient-actions">{slots.map(slot=><button type="button" className={`patient-button ${time===slot?'':'secondary'}`} key={slot} onClick={()=>setTime(slot)}>{slot}</button>)}</div>{!slots.length&&<p>{t('noSlots')}</p>}</fieldset>}{error&&<div className="patient-alert error">{error}</div>}<button className="patient-button" disabled={!time||loading}>{loading?t('loading'):t('confirmBooking')}</button></form></section>}

export function Appointments(){const{t,i18n}=useTranslation();const[group,setGroup]=useState('upcoming');const{data,error,loading}=useApi(`/api/patient/appointments?group=${group}`);return <State loading={loading} error={error}><h1>{t('myAppointments')}</h1><div className="patient-tabs">{['upcoming','past','cancelled','all'].map(x=><button className={`patient-button ${group===x?'':'secondary'}`} onClick={()=>setGroup(x)} key={x}>{t(x)}</button>)}</div>{!data?.length?<Empty>{t('noAppointments')}</Empty>:<div className="patient-list">{data.map(a=><article className="patient-card patient-row" key={a.id}><div><h2>{doctorName(a.doctor,i18n.language)}</h2><p>{a.appointmentDate} · {a.appointmentTime} · {a.status}</p></div><Link className="patient-button secondary" to={`/patient/appointments/${a.id}`}>{t('details')}</Link></article>)}</div>}</State>}
export function AppointmentDetails(){const{id}=useParams();const{t,i18n}=useTranslation();const{data,error,loading,reload}=useApi(`/api/patient/appointments/${id}`);const[actionError,setActionError]=useState('');async function cancel(){try{await apiRequest(`/api/patient/appointments/${id}/cancel`,{method:'POST'});reload()}catch(e){setActionError(e.message)}}return <State loading={loading} error={error}><article className="patient-card"><h1>{t('appointmentDetails')}</h1><h2>{doctorName(data.doctor,i18n.language)}</h2><p>{data.appointmentDate} · {data.appointmentTime}</p><p>{data.status}</p>{actionError&&<div className="patient-alert error">{actionError}</div>}{['PENDING','SCHEDULED','CONFIRMED'].includes(data.status)&&<div className="patient-actions"><Link className="patient-button secondary" to={`/patient/appointments/${id}/reschedule`}>{t('rescheduleAppointment')}</Link><button className="patient-button" onClick={cancel}>{t('cancelAppointment')}</button></div>}</article></State>}

export function LabResults(){return <Collection path="/api/patient/lab-results" titleKey="labResults" render={item=><><h2>{new Date(item.orderDate).toLocaleDateString()}</h2>{item.tests.map(test=><p key={test.id}>{test.service.labelEn}: <strong>{test.resultValue}</strong></p>)}</>}/>}
export function Prescriptions(){return <Collection path="/api/patient/prescriptions" titleKey="prescriptions" render={item=><><h2>{new Date(item.prescriptionDate).toLocaleDateString()}</h2>{item.medicines.map(m=><p key={m.id}>{m.medicine.labelEn} — {m.dosage}, {m.duration}</p>)}</>}/>}
export function MedicalRecords(){return <Collection path="/api/patient/medical-records" titleKey="medicalRecords" render={item=><><h2>{new Date(item.visitDate).toLocaleDateString()}</h2><p><strong>Diagnosis:</strong> {item.diagnosis}</p><p><strong>Treatment:</strong> {item.treatment}</p></>}/>}
function Collection({path,titleKey,render}){const{t}=useTranslation();const{data,error,loading}=useApi(path);return <State loading={loading} error={error}><h1>{t(titleKey)}</h1>{!data?.length?<Empty>{t('noRecords')}</Empty>:data.map(item=><article className="patient-card" key={item.id}>{render(item)}</article>)}</State>}
export function Profile(){const{t}=useTranslation();const{data,error,loading,reload}=useApi('/api/patient/me');const[form,setForm]=useState(null),[message,setMessage]=useState('');useEffect(()=>{if(data)setForm({addressStateId:data.addressStateId,addressDetails:data.addressDetails||'',emergencyContact:data.emergencyContact||'',preferredLanguage:data.preferredLanguage})},[data]);async function save(e){e.preventDefault();await apiRequest('/api/patient/me',{method:'PATCH',body:JSON.stringify(form)});setMessage(t('saved'));reload()}return <State loading={loading} error={error}>{form&&<section className="patient-card"><h1>{t('profile')}</h1><p>{data.fullNameEn}</p><p>{data.phone} · {data.email}</p><form onSubmit={save}><label className="patient-field">{t('addressState')}<input type="number" min="1" max="18" value={form.addressStateId} onChange={e=>setForm({...form,addressStateId:e.target.value})}/></label><label className="patient-field">{t('addressDetails')}<input value={form.addressDetails} onChange={e=>setForm({...form,addressDetails:e.target.value})}/></label><label className="patient-field">{t('emergencyContact')}<input value={form.emergencyContact} onChange={e=>setForm({...form,emergencyContact:e.target.value})}/></label>{message&&<div className="patient-alert success">{message}</div>}<button className="patient-button">{t('save')}</button></form></section>}</State>}
