import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { apiRequest } from '../../services/apiClient';
import StatusBadge from '../../components/ui/StatusBadge';
import { CalendarDays, FlaskConical, Pill, Search, Stethoscope } from 'lucide-react';
import Dialog from '../../components/ui/Dialog';

function useApi(path){const[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const reload=()=>{setLoading(true);apiRequest(path).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(reload,[path]);return{data,error,loading,reload}}
function State({loading,error,children}){if(loading)return <div className="patient-card">Loading…</div>;if(error)return <div className="patient-alert error" role="alert">{error}</div>;return children}
function Empty({children}){return <div className="patient-card patient-empty">{children}</div>}
const doctorName=(doctor,lang)=>lang==='ar'?doctor?.fullNameAr:doctor?.fullNameEn;

export function Dashboard(){const{t,i18n}=useTranslation();const profile=useApi('/api/patient/me');const appointments=useApi('/api/patient/appointments?group=upcoming');const labs=useApi('/api/patient/lab-results');const prescriptions=useApi('/api/patient/prescriptions');if(profile.error?.includes('not linked'))return <><div className="patient-alert error">{profile.error}</div><Link className="patient-button" to="/patient/claim">{t('claimRecord')}</Link></>;const next=appointments.data?.[0];return <State loading={profile.loading} error={profile.error}><h1>{t('patientHome')}</h1><section className="patient-card" style={{background:'linear-gradient(135deg,#0f5ec9,#3e9bf3)',color:'#fff',border:0}}><p style={{color:'#dcecff'}}>{t('welcome')}</p><h2 style={{color:'#fff',fontSize:'clamp(1.6rem,4vw,2.4rem)'}}>{profile.data?.fullNameEn}</h2><Link className="patient-button" style={{background:'#fff',color:'var(--color-primary)',marginTop:'1rem'}} to="/patient/doctors"><Stethoscope size={18}/>{t('bookAppointment')}</Link></section>{next&&<section className="patient-card"><p>{t('upcomingAppointments')}</p><h2>{doctorName(next.doctor,i18n.language)}</h2><div className="patient-row"><div><CalendarDays size={18}/> {next.appointmentDate} · {next.appointmentTime}</div><StatusBadge status={next.status}/><Link className="patient-button secondary" to={`/patient/appointments/${next.id}`}>{t('details')}</Link></div></section>}<div className="patient-grid"><Summary icon={<CalendarDays/>} title={t('upcomingAppointments')} value={appointments.data?.length||0}/><Summary icon={<FlaskConical/>} title={t('recentLabResults')} value={labs.data?.length||0}/><Summary icon={<Pill/>} title={t('prescriptions')} value={prescriptions.data?.length||0}/></div></State>}
function Summary({icon,title,value}){return <div className="patient-card"><div style={{color:'var(--color-primary)'}}>{icon}</div><h3>{title}</h3><strong>{value}</strong></div>}

export function Doctors(){const{t,i18n}=useTranslation();const{data,error,loading}=useApi('/api/patient/doctors');const[query,setQuery]=useState('');const[specialty,setSpecialty]=useState('');const specialties=[...new Set((data||[]).map(d=>i18n.language==='ar'?d.specialtyAr:d.specialtyEn).filter(Boolean))];const filtered=(data||[]).filter(d=>{const name=doctorName(d,i18n.language)||'';const spec=i18n.language==='ar'?d.specialtyAr:d.specialtyEn;return(!query||`${name} ${spec}`.toLowerCase().includes(query.toLowerCase()))&&(!specialty||spec===specialty)});return <State loading={loading} error={error}><h1>{t('doctors')}</h1><div className="patient-card"><div className="patient-grid"><label className="patient-field"><span>{t('search')}</span><span style={{position:'relative'}}><Search size={18} style={{position:'absolute',insetInlineStart:'.8rem',top:'.9rem',color:'var(--color-text-muted)'}}/><input style={{paddingInlineStart:'2.6rem',width:'100%'}} value={query} onChange={e=>setQuery(e.target.value)}/></span></label><label className="patient-field"><span>{t('selectSpecialty')}</span><select value={specialty} onChange={e=>setSpecialty(e.target.value)}><option value="">{t('all')}</option>{specialties.map(s=><option key={s}>{s}</option>)}</select></label></div></div>{!filtered.length?<Empty>{t('noDoctors')}</Empty>:<div className="patient-grid">{filtered.map(d=><article className="patient-card" key={d.id}><div style={{width:'54px',height:'54px',display:'grid',placeItems:'center',borderRadius:'16px',background:'var(--color-primary-soft)',color:'var(--color-primary)',fontSize:'1.25rem',fontWeight:800,marginBottom:'1rem'}}>{doctorName(d,i18n.language)?.split(' ').slice(0,2).map(x=>x[0]).join('')}</div><h2>{doctorName(d,i18n.language)}</h2><p>{i18n.language==='ar'?d.specialtyAr:d.specialtyEn}</p><p style={{margin:'1rem 0',fontWeight:750,color:'var(--color-text)'}}>{Number(d.consultationFee).toLocaleString()} SDG</p><div className="patient-actions"><Link className="patient-button secondary" to={`/patient/doctors/${d.id}`}>{t('details')}</Link><Link className="patient-button" to={`/patient/book/${d.id}`}>{t('book')}</Link></div></article>)}</div>}</State>}
export function DoctorDetails(){const{id}=useParams();const{t,i18n}=useTranslation();const{data,error,loading}=useApi(`/api/patient/doctors/${id}`);return <State loading={loading} error={error}><article className="patient-card"><h1>{doctorName(data,i18n.language)}</h1><p>{i18n.language==='ar'?data.specialtyAr:data.specialtyEn}</p><p>{Number(data.consultationFee).toLocaleString()} SDG</p><Link className="patient-button" to={`/patient/book/${id}`}>{t('bookAppointment')}</Link></article></State>}
export function BookAppointment(){const{doctorId}=useParams();const{t}=useTranslation();const nav=useNavigate();const[date,setDate]=useState(''),[slots,setSlots]=useState([]),[time,setTime]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);useEffect(()=>{if(date)apiRequest(`/api/appointments/slots?doctorId=${doctorId}&date=${date}`).then(setSlots).catch(e=>setError(e.message))},[doctorId,date]);async function submit(e){e.preventDefault();setLoading(true);setError('');try{const app=await apiRequest('/api/patient/appointments',{method:'POST',body:JSON.stringify({doctorId,appointmentDate:date,appointmentTime:time})});nav(`/patient/appointments/${app.id}`)}catch(e){setError(e.message)}finally{setLoading(false)}}return <section className="patient-card"><h1>{t('bookAppointment')}</h1><form onSubmit={submit}><label className="patient-field">{t('selectDate')}<input type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>{setDate(e.target.value);setTime('')}}/></label>{date&&<fieldset className="patient-card"><legend>{t('selectTime')}</legend><div className="patient-actions">{slots.map(slot=><button type="button" className={`patient-button ${time===slot?'':'secondary'}`} key={slot} onClick={()=>setTime(slot)}>{slot}</button>)}</div>{!slots.length&&<p>{t('noSlots')}</p>}</fieldset>}{error&&<div className="patient-alert error">{error}</div>}<button className="patient-button" disabled={!time||loading}>{loading?t('loading'):t('confirmBooking')}</button></form></section>}

export function Appointments(){const{t,i18n}=useTranslation();const[group,setGroup]=useState('upcoming');const{data,error,loading}=useApi(`/api/patient/appointments?group=${group}`);return <State loading={loading} error={error}><h1>{t('myAppointments')}</h1><div className="patient-tabs">{['upcoming','past','cancelled','all'].map(x=><button className={`patient-button ${group===x?'':'secondary'}`} onClick={()=>setGroup(x)} key={x}>{t(x)}</button>)}</div>{!data?.length?<Empty>{t('noAppointments')}</Empty>:<div className="patient-list">{data.map(a=><article className="patient-card patient-row" key={a.id}><div><h2>{doctorName(a.doctor,i18n.language)}</h2><p>{a.appointmentDate} · {a.appointmentTime}</p><StatusBadge status={a.status}/></div><Link className="patient-button secondary" to={`/patient/appointments/${a.id}`}>{t('details')}</Link></article>)}</div>}</State>}
export function AppointmentDetails(){const{id}=useParams();const{t,i18n}=useTranslation();const{data,error,loading,reload}=useApi(`/api/patient/appointments/${id}`);const[actionError,setActionError]=useState('');const[confirming,setConfirming]=useState(false);const[cancelling,setCancelling]=useState(false);async function cancel(){setCancelling(true);setActionError('');try{await apiRequest(`/api/patient/appointments/${id}/cancel`,{method:'POST'});setConfirming(false);reload()}catch(e){setActionError(e.message)}finally{setCancelling(false)}}return <State loading={loading} error={error}><article className="patient-card"><h1>{t('appointmentDetails')}</h1><StatusBadge status={data.status}/><h2 style={{marginTop:'1.25rem'}}>{doctorName(data.doctor,i18n.language)}</h2><p>{data.appointmentDate} · {data.appointmentTime}</p><p>#{String(data.id).slice(0,8).toUpperCase()}</p>{actionError&&<div className="patient-alert error">{actionError}</div>}{['PENDING','SCHEDULED','CONFIRMED'].includes(data.status)&&<div className="patient-actions" style={{marginTop:'1.25rem'}}><Link className="patient-button secondary" to={`/patient/appointments/${id}/reschedule`}>{t('rescheduleAppointment')}</Link><button className="patient-button" onClick={()=>setConfirming(true)}>{t('cancelAppointment')}</button></div>}<Dialog open={confirming} onClose={()=>!cancelling&&setConfirming(false)} title={t('cancelAppointmentQuestion')} description={t('cancelWarning')}><div className="ui-dialog__details"><strong>{doctorName(data.doctor,i18n.language)}</strong><span>{data.appointmentDate}</span><span>{data.appointmentTime}</span></div>{actionError&&<div className="patient-alert error" role="alert">{actionError}</div>}<div className="ui-dialog__actions"><button className="ui-button ui-button--outline" autoFocus onClick={()=>setConfirming(false)} disabled={cancelling}>{t('keepAppointment')}</button><button className="ui-button ui-button--danger" onClick={cancel} disabled={cancelling} aria-busy={cancelling}>{cancelling?t('loading'):t('cancelAppointment')}</button></div></Dialog></article></State>}

export function LabResults(){return <Collection path="/api/patient/lab-results" titleKey="labResults" render={item=><><h2>{new Date(item.orderDate).toLocaleDateString()}</h2>{item.tests.map(test=><p key={test.id}>{test.service.labelEn}: <strong>{test.resultValue}</strong></p>)}</>}/>}
export function Prescriptions(){return <Collection path="/api/patient/prescriptions" titleKey="prescriptions" render={item=><><h2>{new Date(item.prescriptionDate).toLocaleDateString()}</h2>{item.medicines.map(m=><p key={m.id}>{m.medicine.labelEn} — {m.dosage}, {m.duration}</p>)}</>}/>}
export function MedicalRecords(){return <Collection path="/api/patient/medical-records" titleKey="medicalRecords" render={item=><><h2>{new Date(item.visitDate).toLocaleDateString()}</h2><p><strong>Diagnosis:</strong> {item.diagnosis}</p><p><strong>Treatment:</strong> {item.treatment}</p></>}/>}
function Collection({path,titleKey,render}){const{t}=useTranslation();const{data,error,loading}=useApi(path);return <State loading={loading} error={error}><h1>{t(titleKey)}</h1>{!data?.length?<Empty>{t('noRecords')}</Empty>:data.map(item=><article className="patient-card" key={item.id}>{render(item)}</article>)}</State>}
export function Profile(){const{t}=useTranslation();const{data,error,loading,reload}=useApi('/api/patient/me');const[form,setForm]=useState(null),[message,setMessage]=useState('');const[saving,setSaving]=useState(false);useEffect(()=>{if(data)setForm({addressStateId:data.addressStateId,addressDetails:data.addressDetails||'',emergencyContact:data.emergencyContact||'',preferredLanguage:data.preferredLanguage})},[data]);async function save(e){e.preventDefault();setSaving(true);try{await apiRequest('/api/patient/me',{method:'PATCH',body:JSON.stringify(form)});setMessage(t('saved'));reload()}finally{setSaving(false)}}return <State loading={loading} error={error}>{form&&<><section className="patient-card"><h1>{t('profile')}</h1><h2>{data.fullNameEn}</h2><p>{data.phone}{data.email?` · ${data.email}`:''}</p><form onSubmit={save}><label className="patient-field">{t('addressState')}<input type="number" min="1" max="18" value={form.addressStateId} onChange={e=>setForm({...form,addressStateId:e.target.value})}/></label><label className="patient-field">{t('addressDetails')}<input value={form.addressDetails} onChange={e=>setForm({...form,addressDetails:e.target.value})}/></label><label className="patient-field">{t('emergencyContact')}<input value={form.emergencyContact} onChange={e=>setForm({...form,emergencyContact:e.target.value})}/></label>{message&&<div className="patient-alert success">{message}</div>}<button className="patient-button" disabled={saving}>{saving?t('loading'):t('save')}</button></form></section><section className="patient-card"><h2>{t('accountSecurity')}</h2><p>{t('phone')}: <StatusBadge status={data.phoneVerified?'CONFIRMED':'PENDING'}/></p>{data.email&&<p>{t('emailOptional')}: <StatusBadge status={data.emailVerified?'CONFIRMED':'PENDING'}/></p>}</section></>}</State>}
