-- Permanent clinic file numbers are generated by PostgreSQL, not by clients.
CREATE SEQUENCE "patient_file_number_seq"
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
  NO CYCLE;

ALTER TABLE "Patient" ADD COLUMN "fileNumber" TEXT;

-- Backfill deterministically. Sequence gaps are intentional and are never reused.
DO $$
DECLARE
  patient_row RECORD;
BEGIN
  FOR patient_row IN
    SELECT "id"
    FROM "Patient"
    WHERE "fileNumber" IS NULL
    ORDER BY "createdAt" ASC, "id" ASC
  LOOP
    UPDATE "Patient"
    SET "fileNumber" = 'SHF-' || lpad(nextval('"patient_file_number_seq"')::text, 6, '0')
    WHERE "id" = patient_row."id";
  END LOOP;
END $$;

DO $$
DECLARE
  total_count BIGINT;
  populated_count BIGINT;
  distinct_count BIGINT;
  invalid_count BIGINT;
BEGIN
  SELECT count(*) INTO total_count FROM "Patient";
  SELECT count(*) INTO populated_count FROM "Patient" WHERE "fileNumber" IS NOT NULL;
  SELECT count(DISTINCT "fileNumber") INTO distinct_count FROM "Patient";
  SELECT count(*) INTO invalid_count
  FROM "Patient"
  WHERE "fileNumber" !~ '^SHF-[0-9]+$';

  IF total_count <> populated_count OR total_count <> distinct_count OR invalid_count <> 0 THEN
    RAISE EXCEPTION 'Patient file number backfill verification failed';
  END IF;
END $$;

ALTER SEQUENCE "patient_file_number_seq" OWNED BY "Patient"."fileNumber";
ALTER TABLE "Patient"
  ALTER COLUMN "fileNumber" SET DEFAULT ('SHF-'::text || lpad(nextval('"patient_file_number_seq"'::regclass)::text, 6, '0'::text)),
  ALTER COLUMN "fileNumber" SET NOT NULL;

CREATE UNIQUE INDEX "Patient_fileNumber_key" ON "Patient"("fileNumber");

CREATE OR REPLACE FUNCTION "prevent_patient_file_number_change"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW."fileNumber" IS DISTINCT FROM OLD."fileNumber" THEN
    RAISE EXCEPTION 'Patient file number is immutable' USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "Patient_fileNumber_immutable"
BEFORE UPDATE OF "fileNumber" ON "Patient"
FOR EACH ROW
EXECUTE FUNCTION "prevent_patient_file_number_change"();
